from . import menu_item
from . import event_booking
from . import catering_service
from . import feedback
from . import whatsapp_integration
from . import res_partner_extend
from . import account_move_extend
from . import dashboard
from . import reports